ALTER TABLE maintenance
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN scheduled_date TYPE TIMESTAMP WITH TIME ZONE;